{{- if .Values.kubesphereAsOIDCProvider.enabeld }}
apiVersion: v1
kind: Secret
metadata:
  name: oauthclient-open-webui
  namespace: kubesphere-system
  labels:
    config.kubesphere.io/oauthclient: open-webui
    config.kubesphere.io/type: oauthclient
type: config.kubesphere.io/oauthclient
stringData:
  configuration.yaml: |
    name: open-webui
    secret: open-webui
    grantMethod: auto
    trusted: true
    scopeRestrictions:
      - 'openid'
      - 'email'
      - 'profile'
    redirectURIs:
      - {{ .Values.openWebUIUrl }}/oauth/oidc/callback
{{- end }}