apiVersion: kubesphere.io/v1alpha1
name: holmesgpt
version: 0.12.4
displayName:
  zh: HolmesGPT
  en: HolmesGPT
description:
  zh: AI Agent for Troubleshooting Cloud-Native Environments.
  en: AI Agent for Troubleshooting Cloud-Native Environments.
category: ai-machine-learning
keywords:
  - ai-machine-learning
home: https://kubesphere.io
sources:
  - https://github.com/kubesphere
kubeVersion: ">=1.19.0-0"
ksVersion: ">=4.0.0-0"
maintainers:
  - name: "kubesphere"
    email: "kubesphere@yunify.com"
    url: "kubesphere.io"
provider:
  zh:
    name: "kubesphere"
    email: "kubesphere@yunify.com"
    url: "kubesphere.io"
  en:
    name: "kubesphere"
    email: "kubesphere@yunify.com"
    url: "kubesphere.io"
icon: ./static/logo.png
dependencies:
  - name: holmes
    tags:
    - extension
  - name: holmesgpt-frontend
    tags:
    - extension
# installationMode describes how to install subcharts, it can be HostOnly or Multicluster.
# In Multicluster mode, the subchart with tag `extension` will only be deployed to the host cluster,
# and the subchart with tag `agent` will be deployed to all selected clusters.
installationMode: HostOnly
# Custom namespace example: If not specified, it will be installed in the namespace named extension-{name}.
#namespace: ""
# external dependencies example
#externalDependencies:
#  - name: a
#    type: extension
#    version: ">= 2.6.0"
#    required: true
#  - name: b
#    type: extension
#    version: ">= 2.2.0"
#    required: true
# Add init containers to the extension installation job to execute custom tasks (eg: CRDs upgrade).
# Support unified or separate configuration of init container image for each stage.
#annotations:
#  executor-hook-image.kubesphere.io: ...
#  executor-hook-image.kubesphere.io/install: ...
#  executor-hook-image.kubesphere.io/upgrade: ...
#  executor-hook-image.kubesphere.io/uninstall: ...
