apiVersion: v2
name: holmesgpt-frontend
description: Frontend of holmesGPT extension.
type: application
version: 0.2.0
appVersion: "v0.2.0"
home: https://kubesphere.io
sources:
  - https://github.com/kubesphere

