// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // --------------------------------------------------------------------------
  // docs 模块侧边栏（基于 docs/ 目录自动生成）
  // --------------------------------------------------------------------------
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // --------------------------------------------------------------------------
  // extensions 模块侧边栏（基于 extensions/ 目录自动生成）
  // --------------------------------------------------------------------------
  extensionsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // --------------------------------------------------------------------------
  // 手动创建 sidebar 示例（如需自定义，可参考下面注释）
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */
};

export default sidebars;
