name: Build & Package Extensions

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download ksbuilder
        run: |
          curl -L https://github.com/kubesphere/ksbuilder/releases/download/v0.4.5/ksbuilder_0.4.5_linux_amd64.tar.gz -o ksbuilder.tar.gz
          tar -zxvf ksbuilder.tar.gz
          sudo mv ksbuilder /usr/local/bin/ksbuilder
          chmod +x /usr/local/bin/ksbuilder

      - name: Package All Extensions
        run: |
          mkdir -p .extension-museum
          cd .extension-museum
          for ext in $(ls ../extensions); do
            if [ -d "../extensions/$ext/config/$ext" ]; then
              echo "Packaging $ext..."
              ksbuilder package "../extensions/$ext/config/$ext"
            fi
          done

      - name: Commit & Push .extension-museum updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .extension-museum || true
          if ! git diff --cached --quiet; then
            git commit -m "Update .extension-museum for $GITHUB_REF_NAME"
            git push
          else
            echo "No changes in .extension-museum"
          fi
